### ISSUE TITLE
Use long-lived TCP connections.

### ISSUE THREAD

**Issue by benrob0329** [MCMrARM/revolution-irc#115]
Right now, Android puts the network to sleep for intervals which appear to be greater than the ping timeout of the network connection, and Revolution IRC doesn't override this for PING responses.

Theoretically, the messages would sit in the server send-que (tcp level packet que) until they were received by the client (the network is brought back from sleep). However, either the client would need to blindly send PONGs at constant intervals to try and keep the connection alive, or would need to override the battery-saving network sleep and receive packets (even if at set intervals relating to the ping timeout).

**Comment by MCMrARM** [comment]
I'm, unfortunately, unsure how can I do this. Only think I can think of is to do a wakelock of some sort, but that'll negatively affect the battery life of the whole device too much to be a reasonable solution.
Also I am unsure whether your hypothesis is correct. The unregistered disconnection issue only happens on Wi-Fi for me, not on 3G, and appears to be caused by the Wi-Fi somehow dropping the connection, not really by Revo not responding to server PINGs, but rather by a TCP-level issue.
What I could think of is to add an option to send PINGs at a constant interval from the client. This should allow Android to at least register that the connection is no longer alive.

**Comment by LuccoJ** [comment]
I think having a configurable client-initiated PING would be a good feature in any case, as a carrier's network may require keepalives to avoid dropping the connection more frequently than a given IRC server sends its own PING, and only the client can know that.

**Comment by MCMrARM** [comment]
Some work has been done: https://github.com/MCMrARM/revolution-irc/commit/56c7ee508985ca9b6c022cfc3d78c459338e922f
This still needs to be made configurable so the issue is not closed yet.

**Comment by MCMrARM** [comment]
Implemented configuration settings: https://github.com/MCMrARM/revolution-irc/commit/c36f9d3bf11f0b23a3c5473562fb4e2f5df8fdfb
