### ISSUE TITLE
Dowloaded it and couldn't even get it to START on Undernet

### ISSUE THREAD

**Issue by trennor** [MCMrARM/revolution-irc#116]
Extremely disappointed, running it on Android, got it all set up (so I thought), with nicks, login commands, the whole bit, went to run the Undernet server, and it puked. Can't seem to get any colors right, I can find no support to help me along with questions, 63 mb and and it doesn't even RUN?! Wasted over half an hour pissing around with this and got nowhere. Totally fail.

**Comment by michcioperz** [comment]
Extremely disappointed, getting emails for tickets like this. I went here and it looks like someone puked. 379 characters and the issue doesn't even describe anything we could use to resolve it. Wasted over 5 seconds reading this. Totally fail.

**Comment by benrob0329** [comment]
I can't tell if this is someone trolling, or who just desperately needs some sysadmin basics.

In case its someone legit, here's a tip: Dont run a server on Android, and don't try to run software not made for Android on Android.

**Comment by michcioperz** [comment]
Nah, I think they tried to connect to the Undernet network (some vague slang where running means connecting to)

**Comment by michcioperz** [comment]
Dear @trennor, you have come here and yelled at a one-person-team (not me particularly) for a beta version of an app being somehow unable to fulfill your request. You have provided no useful info that could get any of us any close to the solution. The only lead is the Undernet network, which probably breaks the IRC compliance this app was built in mind with (guessing from how we do not have much issues with other networks). Please come back once you've calmed down, when you're ready to respectfully ask for help instead of pointlessly attacking people.

**Comment by trennor** [comment]
Fix it so it runs for a dummy using an android phone! Not everyone's a
geek, you know!! I had to buy another client because this one didnt work as
advertised, wouldn't auto-command, couldn't save the server data, what
friggin' good is that?! I HATE wasting time over shit that doesn't work!
FEEL My frustration. AND I'm experienced with Linux AND IRC, but I
shouldn't have  had these problems.

**Comment by michcioperz** [comment]
I'm glad you didn't explain what exactly didn't work and how come it ended up weighing 63 MB (which it doesn't) cause now we can just close the issue.

**Comment by MCMrARM** [comment]
Hello,
first of all this client is made only by me in my spare time, for no revenue. It's not fully "finished" either, with some features not being implemented yet and with bugs. It's still in a beta stage.

The client weights around 3MB. I don't know what weighted 63MB in the app you downloaded, but no version released by me should weight so much. The official distribution channels are Google Play and F-Droid.

I'm pretty sure you did not send my any E-Mail or attempt to contact me on IRC, I do not check Google Play reviews too often so it is possible you haven't got a reply yet.

If the app crashes, please attach a LogCat and reopen the issue. If you run into a bug, please create a new issue explaining the bug with as many issues as possible. If you are missing a feature, please open an issue with the feature request (one per issue). Otherwise, this is not the place for discussion, which #revolutionirc on Freenode is for.

**Comment by trennor** [comment]
if it's not fully functional then it shouldn't be made available.
incomplete products are never appreciated. take it down, finish it, test
it  extensively before releasing it  on an unsuspecting public. this half
completed crap is bullshit, you should know better. half that crap on
playstore is the same, why you're doing it too is beyond me. it LOOKS nice,
but that's about all i'll give. that's it, I'm done. quit 'making excuses
for it. it's shoddy work which shouldn't be available until it's completely
functional across ALL platforms: phones, tabs, whatever. and that's my
point. for what it's worth. and you evidently don't think it's worth much,
so to hell with it.

**Comment by TofuLynx** [comment]
@trennor You're being ridiculous. You are spelling out words without any real meaning or help for the developer, which is spending valuable time making this IRC client and reading your concerns. You should be more collaborative and help him with logs and statements about the issue in question. I am very grateful for this client and I love the application!

**Comment by michcioperz** [comment]
@trennor I know in real life alone 5 people who prefer this over other clients so to hell with your arguments. You are not interested in this app and so be it.
@MCMrARM please lock the thread, it's not going to get any better.

**Comment by benrob0329** [comment]
>so to hell with it

I completely agree, why should we use something that works *most of the time*, if the person making it can't be bothered to quit their job and work on it full time? We need more homeless devs who spend all their time writing code under that bridge over there.

Seriously though, revolution irc works better than any other mobile client I've used, and certainly does not deserve to be lumped in with "half the crap on the Play Store". Frankly, I'm appalled at your ignorance (or maybe lack or respect) to other people's time.

But really, the download is not 63 megs, you might want to run a virus scan or just wipe your phone completely just in case.

**Comment by MCMrARM** [comment]
Hello,
there is plenty of commercial unfinished software you have actually have to pay for. The client is marked as *unreleased* on the Google Play store for an reason, if you don't want to use unfinished software, simply avoid *unreleased* software which is perhaps tagged this way for a reason?

I'm closing this.
