### ISSUE TITLE
Unable to remove heads-up notification.

### ISSUE THREAD

**Issue by Harkaan** [MCMrARM/revolution-irc#146]
I would like to have my notifications to act just like the setting "High" on Oreo notifications: vibrate/sound but no heads-up notification (the banner that appears at the top of the screen and displays the message).
The "notification" menu on my phone for Revolution IRC does not display Oreo settings but rather "activate sound", "ignore busy settings", etc. If I disable the sound, I have no heads-up notification but no vibration either. If I activate it, I have both, no matter how I configure the notifications in-app.
Strangely enough, the notification category for the status of the app allows Oreo settings. Shouldn't the notifications from messages/notices etc allow it too ?
Many thanks.
PS I'm on a OnePlus 5T

**Comment by MCMrARM** [comment]
There were two sub-issues:
- The settings did not allow disabling heads-up notifications, because the priority picker was broken and the notifications were always posted with importance set to high. This has been fixed with https://github.com/MCMrARM/revolution-irc/commit/d90c2cd320c8960b7011414f59118437ace3b9c9
- On O, some settings are unavailable. This has also been implemented today, with https://github.com/MCMrARM/revolution-irc/commit/cedcdbadf55e1f35f43c957b151a7b400286dfdf
