### ISSUE TITLE
Make showing member list obvious

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/revolution-irc#194]
A lot of people can't figure out the slide from right drawer.

Proposed solutions:
1) Add a tip card when the user first opens a channel.
![Member list](https://mrarm.io/u/Clipboard%202019-02-14%2021-43-37.png)

2) Add a [Member list] button to the [...] menu.
Issue: There are already 6 options there, adding a 7th one crowds the menu too much.

If anyone has any other ideas, please mention them in comments. Otherwise, please vote for your preferred solution.

**Comment by lvenier** [comment]
I would replace the "message user" by the " member list". Selecting a user in the member list would open a message user to the selected nick....

**Comment by TheMythPT** [comment]
Why not using an icon to show the userlist?
Something like Quasseldroid does [here](https://nextcloud.cloudbnc.tk/index.php/s/MKzRRZkK4eibiXX)

Cheers

**Comment by MCMrARM** [comment]
Well, this might end up like that in the redesign.

**Comment by TheMythPT** [comment]
We have space in the `header` bar so, for me it's the logical choice.

PS: also to test the bot in IRC due to some changes in the output

**Comment by jzabroski** [comment]
This behavior is fundamentally broken on my Samsung Note 8 with the Galaxy Edge UX affordances... with the Samsung Android OS, they provide Quick Access drawers for People and Apps... It's a lot like they took the best of DrupE. Let me know if my description is clear. 

So, it is not that I can't figure it out, it's that it's an impossible to express intent due to Samsung Edge. 

Please just put it in the three dots menu. I don't understand the pushback when it seems obvious to me the dots express room properties 

By the way, this is an awesome project. I would love to contribute this as a fix to get my toes wet building Android apps.

**Comment by jzabroski** [comment]
> Why not using an icon to show the userlist?
> Something like Quasseldroid does here?

I got a 404 clicking on it.

**Comment by wnolfm** [comment]
@MCMrARM sliding in from the right doesn't work well when gesture nav is enabled, which is now the default on a lot of new devices. 

The user list could be added to the ... Menu on the right without little issue, there's plenty of room to do so.

**Comment by MCMrARM** [comment]
Yeah it'll probably have to be done, as the amount of work required for the new UI is non trivial and I don't have time to do it right now. I'll try to do it as soon as possible.

**Comment by wnolfm** [comment]
@MCMrARM can you push this change to the play store?
