### ISSUE TITLE
Unable to compile latest revolution from git in Android Studio, getting error.

### ISSUE THREAD

**Issue by roboirc** [MCMrARM/revolution-irc#231]
Please see: https://pasteboard.co/ID7Yifz.png
Unable to compile latest source code in Android Studio.
What am I missing / doing wrong? Thanks!

**Comment by roboirc** [comment]
Please create a readme.md with walkthrough on how to compile and run the latest source code of revolution irc on Android Studio. Thanks!

**Comment by MCMrARM** [comment]
I mean I never had issues with just loading it in Android Studio, REFUSING any Gradle updates then compiling it, so I really don't know.

**Comment by roboirc** [comment]
Right but what about extra lines we may need to put in configuration to include any additional libraries Revo may need?
Could you please create a quick walkthrough for us with any extra libraries we may need to include and what lines in the Gradle to modify? Thanks!

**Comment by roboirc** [comment]
Perhaps put the info in main github Readme.md. Could be helpful for newbies too! Thanks!

**Comment by roboirc** [comment]
Ok thanks!

**Comment by jzabroski** [comment]
https://github.com/Purik/android-studio-docker - If the README.md contained a docker image based off this docker image, then it would be 100% reproducible for newcomers.  We would just build inside a docker container.

**Comment by MCMrARM** [comment]
???????? for that docker thing, that makes literally no sense IMHO.

**Comment by jzabroski** [comment]
Why would that make no sense, literally?

**Comment by MCMrARM** [comment]
Because it provides little to no objective benefit, the build won't even be reproducible because gradle downloads all dependencies at runtime and the Android Studio version is the last of your worries, plus why the hell bring the whole android studio into the build when all you want is gradle. Not to mention that setting up build caching with this is probably going to be a headache (but doable).

That docker image solves a completely different problem. There are some people who want to use Android Studio as an app in a docker container for whatever reasons they have. I don't fully support that idea as-is either, but applying it here makes no sense whatsoever.

**Comment by MCMrARM** [comment]
I'm not saying having a reproducible build system is a bad idea, however just dropping Docker here is probably not a great idea (Docker is unneeded because Android Studio automatically downloads project's gradle version; unfortunately this doesn't make the builds any more reproducible as far as I am aware :/ ; it might make sense for CI purposes though and I might have missed something, feel free to give counterarguments). And having Android Studio in Docker for build purposes is a _terrible idea_.

**Comment by jzabroski** [comment]
I waste more time trying to build new projects than any other task.  Docker is meant to isolate dependencies in such a way to have true "write once run anywhere" deployment descriptors.  The meta-circular nature of the fact you would bootstrap your IDE and code editing with docker does not make it a terrible idea, just a strange, unusual one.

That said, I love the passion.  

Why do you think builds are not reproducible?

**Comment by MCMrARM** [comment]
Why not just docker-ize gradle? This is Android development, this is nowhere like the horror you'd experience when trying to build C++ projects. Plus I'm not sure how'd you imagine the dockerfile for this project should look like, as Android Studio is a GUI tool and not really possible to automate (and dockerfiles for GUI apps are a completely different beast and I imagine that you'd run into a few issues when trying to do anything sane with them). Considering that you can easily download any historic Android Studio version and run it natively, I don't see how inserting Docker would help with anything other than isolation.
I heard of some horror stories involving reproducible builds and Gradle. Gradle pulls the dependencies on runtime, which sometimes might get autoupdated (when defining a dependency version that's not precise, or when the place it dls them from decides to just replace a version) and there are probably some more issues I don't remember about.

**Comment by roboirc** [comment]
I will reopen this issue so people who are not following proper steps find this useful.

**Comment by MCMrARM** [comment]
Did that fix the build for you though?

**Comment by roboirc** [comment]
Yes it worked fine. The biggest mistake I was doing was doing GRADLE BUILDS for revolution irc that were to be refused. Thanks.

**Comment by MCMrARM** [comment]
Then the issue was solved, the issue will be closed.

**Comment by roboirc** [comment]
Is it possible to supress the upgrade gradle for project notification for revolution ?
