### ISSUE TITLE
this doesn't work....

### ISSUE THREAD

**Issue by puddingepoch** [MCMrARM/revolution-irc#239]
this doesn't work.... i don't know why an irc client messes up such simple functions but i guess thats just the foss way
i can't identify on the nick serv at all i can't register,i dentify or anything it says command not found
ALL the android irc clients are just as broken and shitty as this so if you could fix this so at least one of them is not that would be nice

god foss people dissapoint me

**Comment by Rushi98** [comment]
Does it work on PC clients with same network as phone?

I have faced problem with IRC on some network (university network) both on mobile and PC clients.

Since, the clients work perfectly well for most of the users, there must be something special in your case. Maybe try finding out that speciality before starting blaming others who don't owe you anything.

**Comment by MCMrARM** [comment]
To be honest I don't even know what is their issue, I presume they tried to do shit like `/nickserv` that will obviously not work because there's no alias for that and you have to do '/msg NickServ ...'. To be honest we probably should add a larger base of default command aliases so people copying shit from the internet won't come across a "Command not found" error, that they can only wtf at (though to be fair, whatever manual suggests doing that, should point out that this is a client command generally and it might not work everywhere and suggest messaging NickServ directly).

Because the question is vague I'm closing this as invalid.

**Comment by kurahaupo** [comment]
Maybe have a "deprecated" flag, so that attempting to use an alias results in a pop up warning. Otherwise acquiescing to the junk instructions just further strengthens them.
