### ISSUE TITLE
Feature Request: list channel users

### ISSUE THREAD

**Issue by mdkuser** [MCMrARM/revolution-irc#240]
Can you please add the feature to show a list of the users in a channel (similar to the list users button in Yaaic)?
I tried with custom command /names but it doesn't work.

**Comment by kurahaupo** [comment]
The channel member list is available by swiping in from the right side.
However this ticket could serve as a request for an alternative method of accessing this list, as that swipe gesture is ineffective on some devices, and also not obvious to a new user.

**Comment by stubb** [comment]
> However this ticket could serve as a request for an alternative method of accessing this list, as that swipe gesture is ineffective on some devices, and also not obvious to a new user.

Swipe gesture switches channel tabs for me.

**Comment by kurahaupo** [comment]
Swiping from the edge of the screen, preferable starting beyond it, should perform differently.

**Comment by stubb** [comment]
> Swiping from the edge of the screen, preferable starting beyond it, should perform differently.
Thanks, that works for me in most cases!

**Comment by prg318** [comment]
Its currently impossible to access the topic and userlist sidebar when gesture navigation is enabled. In order to access the user list, one needs to configure their system to use a fixed navigation bar.

Would be nice to have "/names" implemented at least so this info can be accessible to gesture navigation users.

**Comment by MCMrARM** [comment]
Since gesture navigation is now widespread, probably Members should be added to the top right drop down menu.

**Comment by mbjurstrom** [comment]
> Since gesture navigation is now widespread, probably Members should be added to the top right drop down menu.

That would be much appreciated perhaps also combine it with https://developer.android.com/training/gestures/gesturenav#back-gestures

**Comment by MCMrARM** [comment]
Closing with https://github.com/MCMrARM/revolution-irc/commit/7c2fe66161acc9506cec50420e7da7e32950b6eb

> That would be much appreciated perhaps also combine it with https://developer.android.com/training/gestures/gesturenav#back-gestures
@mbjurstrom that'd be awesome, but as I tried to implement it I got into a problem. It's limited to 200dp, which is actually pretty dumb because I planned to have a custom back navigation gesture in newui, but yeah Google knows better. Feel free to open another issue for that.

**Comment by mbjurstrom** [comment]
> Closing with [7c2fe66](https://github.com/MCMrARM/revolution-irc/commit/7c2fe66161acc9506cec50420e7da7e32950b6eb)
> 
> > That would be much appreciated perhaps also combine it with https://developer.android.com/training/gestures/gesturenav#back-gestures
> 
> @mbjurstrom that'd be awesome, but as I tried to implement it I ran into a problem. It's limited to 200dp, which is actually pretty dumb because I planned to have a custom back navigation gesture in newui, but yeah Google knows better. Feel free to open another issue for that.

That is pretty dumb. Thanks for adding it to the menu anyway. I will create an separate issue for that.
