### ISSUE TITLE
I might be doing something wrong?

### ISSUE THREAD

**Issue by TheMythPT** [MCMrARM/revolution-irc#8]
I've compiled the apk with Android Studio Preview.
It connects to znc 1.7.x but it stalls when you try to do something else.
Any idea?
Thanks in advance

Note: using android 5.1

**Comment by MCMrARM** [comment]
Hello,
Could you please provide more information about the issue? It might be a new issue that was created since the last public release.

If you would like to see if that's the case or not, you could try to compile what's the latest public beta using those commits:
https://github.com/MCMrARM/revolution-irc/commit/fb0faa3851cd66dac25a77a4501c14f8c22f9d2f
https://github.com/MCMrARM/chatlib/commit/7106c714cded0c5481248afa8814c0cb03fb8e03
https://github.com/MCMrARM/chatlib-android/commit/90ef7349ac5423f6d11499c647cf860431bf6708

**Comment by TheMythPT** [comment]
Btw, inside https://github.com/MCMrARM/chatlib there's no gradle.bat so I've copied `gradlew.bat`, `gradle` and another one I don't recall from the main repo

**Comment by TheMythPT** [comment]
That should work or it's an incorrect procedure?

**Comment by MCMrARM** [comment]
It should be alright.

Also, if possible, please check the application logs in Android Studio, remove any personal information from it (usernames, passwords, etc. Note that the password is printed in plaintext somewhere in the log so you will want to remove it) and post it here.

**Comment by TheMythPT** [comment]
![captura de ecra 5](https://user-images.githubusercontent.com/25697531/31083426-f3886d08-a791-11e7-8470-55770ed46acf.png)
this appeared to me

**Comment by MCMrARM** [comment]
I don't know. Are you sure you downloaded and extracted the zip correctly and did not remove the folder contents?

**Comment by TheMythPT** [comment]
i git cloned each repo. then entered `chatlib` and copied `gradlew.bat`, `gradle` file and folder and then followed what you said here:
https://github.com/MCMrARM/revolution-irc/issues/7

**Comment by MCMrARM** [comment]
Can we continue this on #revolutionirc on the Freenode network?
