### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/revolution-irc#89]
From an E-Mail:
> Added custom notification rule to get notifications from all messages
> but disconnecting and reconnecting causes notifications come up twice,
> three times, four times, as i disconnect and reconnect more.
> 
>  Force stopping application fixes the issue but I think it doesn't
> close connection properly.
> 
>  (Tested on my inspIRCd server.)
> 
>  Thanks. 😊

**Comment by notanewbie** [comment]
This happens to me too. A custom notification to catch all messages fires three times, and if I turn off the sound for the notification, it doesn't show up on-screen.

**Comment by MCMrARM** [comment]
If this will still be an issue after the 0.3.3 update, please reopen the issue.

**Comment by notanewbie** [comment]
Okay. Thanks for the update!

The issue seems to be gone, despite the fact that I haven't updated or changed my settings. Notifications about me connecting to the server are still duplicated, but it may be due to the fact that I set it to automatically connect to multiple channels.

I'll let you know what happens after the update is rolled out.

**Comment by MCMrARM** [comment]
This is a duplicate of #17
